-- Add network_devices and workstations tables for expanded CMDB scope
USE cmdb;
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS network_devices (
  id               CHAR(36)     NOT NULL PRIMARY KEY,
  hostname         VARCHAR(128) NOT NULL,
  sn               VARCHAR(64)  NOT NULL UNIQUE,
  asset_tag        VARCHAR(64)  NOT NULL UNIQUE,
  device_type      ENUM('switch','router','firewall','load_balancer') NOT NULL DEFAULT 'switch',
  manufacturer     VARCHAR(32)  NOT NULL,
  model            VARCHAR(64)  NOT NULL,
  firmware_version VARCHAR(64)  NULL,
  cpu_model        VARCHAR(128) NULL,
  cpu_count        INT          NOT NULL DEFAULT 1,
  memory_gb        INT          NOT NULL DEFAULT 0,
  flash_gb         INT          NOT NULL DEFAULT 0,
  mgmt_ip          VARCHAR(64)  NOT NULL,
  mgmt_protocol    ENUM('ssh','snmp','telnet') NOT NULL DEFAULT 'ssh',
  mgmt_port        INT          NOT NULL DEFAULT 22,
  snmp_community   VARCHAR(64)  NULL,
  ssh_username     VARCHAR(64)  NULL,
  ssh_password     VARCHAR(255) NULL,
  biz_ip           VARCHAR(64)  NULL,
  vlan             VARCHAR(32)  NULL,
  port_count       INT          NOT NULL DEFAULT 0,
  port_spec        JSON         NULL,
  idc              VARCHAR(64)  NOT NULL,
  rack             VARCHAR(32)  NOT NULL,
  u_position       VARCHAR(32)  NOT NULL,
  status           ENUM('online','offline','maintenance','retired') NOT NULL DEFAULT 'online',
  owner            VARCHAR(64)  NULL,
  purchase_date    DATE         NULL,
  warranty_end     DATE         NULL,
  tags             JSON         NULL,
  remark           TEXT         NULL,
  created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ndev_status (status),
  INDEX idx_ndev_idc (idc),
  INDEX idx_ndev_type (device_type),
  INDEX idx_ndev_brand (manufacturer)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS workstations (
  id               CHAR(36)     NOT NULL PRIMARY KEY,
  hostname         VARCHAR(128) NOT NULL,
  sn               VARCHAR(64)  NOT NULL UNIQUE,
  asset_tag        VARCHAR(64)  NOT NULL UNIQUE,
  manufacturer     VARCHAR(32)  NOT NULL,
  model            VARCHAR(64)  NOT NULL,
  cpu_model        VARCHAR(128) NOT NULL,
  cpu_count        INT          NOT NULL DEFAULT 1,
  memory_gb        INT          NOT NULL DEFAULT 0,
  disk_type        VARCHAR(32)  NOT NULL DEFAULT 'SSD',
  disk_capacity_gb INT          NOT NULL DEFAULT 0,
  mac_address      VARCHAR(17)  NULL,
  os               VARCHAR(64)  NOT NULL DEFAULT 'Windows 11',
  os_version       VARCHAR(64)  NULL,
  biz_ip           VARCHAR(64)  NULL,
  user_name        VARCHAR(64)  NULL,
  department       VARCHAR(64)  NULL,
  monitors         JSON         NULL,
  office_building  VARCHAR(64)  NULL,
  floor            VARCHAR(32)  NULL,
  seat             VARCHAR(32)  NULL,
  status           ENUM('online','offline','maintenance','retired') NOT NULL DEFAULT 'online',
  purchase_date    DATE         NULL,
  warranty_end     DATE         NULL,
  tags             JSON         NULL,
  remark           TEXT         NULL,
  created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ws_status (status),
  INDEX idx_ws_brand (manufacturer),
  INDEX idx_ws_os (os),
  INDEX idx_ws_dept (department)
) ENGINE=InnoDB;
