-- Terminal Assets table
CREATE TABLE IF NOT EXISTS terminal_assets (
    id CHAR(36) PRIMARY KEY,
    hostname VARCHAR(128) NOT NULL,
    sn VARCHAR(64) NOT NULL UNIQUE,
    asset_tag VARCHAR(64) NOT NULL UNIQUE,
    manufacturer VARCHAR(32) NOT NULL,
    model VARCHAR(64) NOT NULL,
    cpu_model VARCHAR(128) NOT NULL,
    cpu_count INT NOT NULL DEFAULT 1,
    memory_gb INT NOT NULL DEFAULT 0,
    disk_type VARCHAR(32) NOT NULL DEFAULT 'SSD',
    disk_capacity_gb INT NOT NULL DEFAULT 0,
    mac_address VARCHAR(17) DEFAULT NULL,
    os VARCHAR(64) NOT NULL DEFAULT 'Windows 11',
    os_version VARCHAR(64) DEFAULT NULL,
    biz_ip VARCHAR(64) DEFAULT NULL,
    user_name VARCHAR(64) DEFAULT NULL,
    status ENUM('online','offline','maintenance','retired') NOT NULL DEFAULT 'online',
    purchase_date DATETIME DEFAULT NULL,
    warranty_end DATETIME DEFAULT NULL,
    tags JSON DEFAULT NULL,
    remark TEXT DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
